//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakturiFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        public int Faktura_ID { get; set; }
        public Nullable<int> Firm_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Faktura_Status { get; set; }
        public Nullable<double> Faktura_Suma { get; set; }
        public Nullable<System.DateTime> Faktura_DatumIzdavanje { get; set; }
        public Nullable<System.DateTime> Faktura_DatumDospevanje { get; set; }
        public Nullable<double> Faktura_TotalDDV { get; set; }
        public string Faktura_Zabeleska { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Firm Firm { get; set; }
    }
}
