//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FakturiFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using FakturiFirst.Models;

    public partial class MoiFakturi : DbContext
    {
        public MoiFakturi()
            : base("name=MoiFakturi")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Faktura> Fakturas { get; set; }
        public virtual DbSet<Account> Firms { get; set; }
        public virtual DbSet<Products> Products { get; set; }
    }
}
