//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakturiFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firm()
        {
            this.Fakturas = new HashSet<Faktura>();
            this.Products = new HashSet<Product>();
        }
    
        public int Firm_ID { get; set; }
        public string Firm_Name { get; set; }
        public string Firm_Email { get; set; }
        public string Firm_Password { get; set; }
        public string Firm_Address { get; set; }
        public string Firm_City { get; set; }
        public string Firm_State { get; set; }
        public string Firm_PhoneNumber { get; set; }
        public string Firm_WebPage { get; set; }
        public byte[] Firm_Logo { get; set; }
        public byte[] Firm_Signature { get; set; }
        public string Firm_TFN { get; set; }
        public string Firm_TransactionAccount { get; set; }
        public string Firm_Bank { get; set; }
        public string Firm_CityPostCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Fakturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
